
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import re


def cleanHtmlContent(htmlContent):  # Convert HTML and convert unicode chars
    if not htmlContent:
        return ""
    soup = BeautifulSoup(htmlContent, "html.parser")
    rawText = soup.get_text(separator=" ")
    replacements = [
        ("\u2018", "'"),
        ("\u2019", "'"),
        ("\u201c", "'"),
        ("\u201d", "'"),
        ("\u2013", "-"),
        ("\u2014", " - "),
        ("\u2022", "*"),
        ("\u2026", "..."),
        ("\xa0", " "),
        ("\u00a0", " "),
        ('"', "'")
    ]
    cleanText = " ".join(rawText.split())
    for old, new in replacements:
        cleanText = cleanText.replace(old, new)
    return cleanText


def removeDuplicateHeadline(headline, content):
    if not headline or not content:
        return content

    hl = str(headline).strip()
    ct = str(content).strip()
    lowHl = hl.lower()
    lowCt = ct.lower()

    if lowCt.startswith(lowHl):
        remainder = ct[len(hl):].strip()
        remainder = re.sub(r"^[—\-:]+\s*", "", remainder)     # Remove leading punctuation
        return remainder if remainder else ct

    sepPattern = r"(?:\s*[|–—:]+\s*)" + re.escape(hl) + r"\s*"
    match = re.match(sepPattern, ct, re.IGNORECASE)
    if match:
        remainder = ct[match.end():].strip()
        return remainder if remainder else ct

    return ct


def removeBenzingaFooter(content):
    if not content:
        return content

    footerPatterns = [
        r"(?:Copyright|©)\s*(?:20\d{2})?\s*Benzinga",
        r"Content provided by Benzinga",
        r"For more disclaimer.*?(?=https?://)",
        r"https?://www\.benzinga\.com/disclaimer.*?(?=\n\n|\Z)",
        r"This information is provided by Benzinga for informational purposes only",
    ]
    text = str(content)
    for pattern in footerPatterns:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"\n{2,}", "\n\n", text).strip()    # Collapse multiple newlines into two

    removeRightwards = [
        r"read more:",
        r"read next:",
        r"photo courtesy:",
        r"image: "
    ]
    for phrase in removeRightwards:
        if re.search(re.escape(phrase), text, re.IGNORECASE):
            text = text.split(phrase)[0].strip()
    return text


def filterEmpty(row):
    content = str(row.get("content", "")).strip()
    if len(content) < 20:
        return "EMPTY"
    wordCount = row.get("wordCount", 0)
    if wordCount < 10:
        return "EMPTY"
    return None


def filterAutomated(row):
    content = str(row.get("content", "")).strip().lower()
    automatedPattern = "\barticle was generated by Benzinga's automated content engine\b"

    if re.search(automatedPattern, content, re.IGNORECASE):
        return "AUTOMATED"

    return None


def filterTranscripts(row):
    headline = str(row.get("headline", "")).strip().lower()
    content = str(row.get("content", "")).strip().lower()
    wordCount = row.get("wordCount", 0)

    benzingaApiPattern = r"This content is powered by Benzinga APIs"
    if re.search(benzingaApiPattern, content, re.IGNORECASE):
        return "TRANSCRIPT"

    transcriptMarkers = [
        r"\btranscript\b",
        r"\bearnings call\b",
        r"\bconference call\b",
    ]

    for marker in transcriptMarkers:
        if re.search(marker, headline, re.IGNORECASE) and wordCount > 500:
            return "TRANSCRIPT"

    if wordCount > 1500:
        return "TRANSCRIPT"     # Likely a transcript if very long

    return None


def filterOptions(row):
    headline = str(row.get("headline", "")).strip().lower()

    optionAlertPattern = r"\boption alert\b"
    if re.search(optionAlertPattern, headline, re.IGNORECASE):
        return "OPTIONS"

    return None


def filterIfYouInvested(row):
    headline = str(row.get("headline", "")).strip().lower()

    ifYouInvestedMarkers = [
        r"\bif you invested $\b",
        r"\bhere's how much investing $\b",
    ]

    for marker in ifYouInvestedMarkers:
        if re.search(marker, headline, re.IGNORECASE):
            return "IF_YOU_INVESTED"

    return None


