import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import re


# ---------------------------------------------------------------------------
# Cleaning helpers
# ---------------------------------------------------------------------------

def cleanHtmlContent(htmlContent):  # Convert HTML and convert unicode chars
    if not htmlContent:
        return ""
    soup = BeautifulSoup(htmlContent, "html.parser")
    rawText = soup.get_text(separator=" ")
    replacements = [
        ("\u2018", "'"),
        ("\u2019", "'"),
        ("\u201c", "'"),
        ("\u201d", "'"),
        ("\u2013", "-"),
        ("\u2014", " - "),
        ("\u2022", "*"),
        ("\u2026", "..."),
        ("\xa0", " "),
        ("\u00a0", " "),
        ('"', "'")
    ]
    cleanText = " ".join(rawText.split())
    for old, new in replacements:
        cleanText = cleanText.replace(old, new)
    return cleanText


def removeDuplicateHeadline(headline, content):
    if not headline or not content:
        return content

    hl = str(headline).strip()
    ct = str(content).strip()
    lowHl = hl.lower()
    lowCt = ct.lower()

    if lowCt.startswith(lowHl):
        remainder = ct[len(hl):].strip()
        remainder = re.sub(r"^[—\-:]+\s*", "", remainder)     # Remove leading punctuation
        return remainder if remainder else ct

    sepPattern = r"(?:\s*[|–—:]+\s*)" + re.escape(hl) + r"\s*"
    match = re.match(sepPattern, ct, re.IGNORECASE)
    if match:
        remainder = ct[match.end():].strip()
        return remainder if remainder else ct

    return ct


def removeBenzingaFooter(content):
    if not content:
        return content

    footerPatterns = [
        r"(?:Copyright|©)\s*(?:20\d{2})?\s*Benzinga",
        r"Content provided by Benzinga",
        r"For more disclaimer.*?(?=https?://)",
        r"https?://www\.benzinga\.com/disclaimer.*?(?=\n\n|\Z)",
        r"This information is provided by Benzinga for informational purposes only",
    ]
    text = str(content)
    for pattern in footerPatterns:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"\n{2,}", "\n\n", text).strip()    # Collapse multiple newlines into two

    removeRightwards = [
        r"read more:",
        r"read next:",
        r"photo courtesy:",
        r"image: "
    ]
    for phrase in removeRightwards:
        if re.search(re.escape(phrase), text, re.IGNORECASE):
            text = text.split(phrase)[0].strip()
    return text


# ---------------------------------------------------------------------------
# Filtering helpers
#
# Every filter takes a row (dict-like) and returns a reason string if the
# article should be removed, otherwise None. The first matching filter wins.
# ---------------------------------------------------------------------------

def filterBenzingaInsights(row):
    """
    Universally drop 'Benzinga Insights' articles. These are formulaic,
    AI-generated filler with no original reporting value.
    """
    author = str(row.get("author", "")).strip().lower()
    if "benzinga insights" in author:
        return "BENZINGA_INSIGHTS"
    return None


def filterAutomated(row):
    """Articles explicitly flagged as machine generated."""
    content = str(row.get("content", "")).strip().lower()
    automatedPattern = r"article was generated by benzinga's automated content engine"

    if re.search(automatedPattern, content, re.IGNORECASE):
        return "AUTOMATED"

    return None


def filterTradingHalt(row):
    """Exchange trading-halt / circuit-breaker notices (no news value)."""
    headline = str(row.get("headline", "")).strip().lower()

    haltPatterns = [
        r"trading halt",
        r"halt news pending",
        r"halted",
        r"resume trade",
        r"resumes trading",
        r"circuit breaker",
        r"trading update",
    ]
    for pattern in haltPatterns:
        if re.search(pattern, headline, re.IGNORECASE):
            return "TRADING_HALT"

    return None


def filterDataFeed(row):
    """
    Automated data dumps from the news wire: 'Reported Thursday' wires,
    macro/PMI releases, analyst price-target changes, corporate-action
    notices, and live CNBC trade alerts. These carry no editorial content.
    Note: we deliberately do NOT drop articles just because they are short /
    empty - sentiment is headline-driven, so a headline-only wire is still
    usable unless it matches one of the useless data-feed patterns below.
    """
    headline = str(row.get("headline", "")).strip().lower()

    dataFeedPatterns = [
        r"^reported (monday|tuesday|wednesday|thursday|friday|saturday|sunday)",
        r"purchasing managers index",
        r"nationwide hpi",
        r"maintains (buy|neutral|hold|overweight|outperform|market perform)",
        r"reiterates (buy|neutral|hold|overweight|outperform|market perform)",
        r"reinstates (buy|neutral|hold|overweight|outperform|market perform)",
        r"upgrades .* to (overweight|outperform)",
        r"initiates coverage on",
        r"raises price target",
        r"lowers price target",
        r"announces price target",
        r"files for mixed shelf",
        r"raises dividend",
        r"reverse stock split",
        r"noncompliance (notification|notice)",
        r"live on cnbc",
        r"final trades",
        r"option alert",
        r"begins trading on",
        r"starts trading on",
        r"delist",
        r"suspend",
    ]
    for pattern in dataFeedPatterns:
        if re.search(pattern, headline, re.IGNORECASE):
            return "DATA_FEED"

    return None


def filterTranscripts(row):
    headline = str(row.get("headline", "")).strip().lower()
    content = str(row.get("content", "")).strip().lower()
    wordCount = row.get("wordCount", 0)

    benzingaApiPattern = r"This content is powered by Benzinga APIs"
    if re.search(benzingaApiPattern, content, re.IGNORECASE):
        return "TRANSCRIPT"

    transcriptMarkers = [
        r"\btranscript\b",
        r"\bearnings\b",
        r"\bconference call\b",
        r"\bwebcast\b",
    ]
    matches = [marker for marker in transcriptMarkers if re.search(marker, headline, re.IGNORECASE)]
    matchCount = len(matches)
    if matchCount >= 2 and transcriptMarkers[0] in matches:
        return "TRANSCRIPT"

    if wordCount > 3600:
        return "TRANSCRIPT"     # Likely a transcript if very long

    return None


def filterOptions(row):
    headline = str(row.get("headline", "")).strip().lower()

    optionAlertPattern = r"\boption alert\b"
    if re.search(optionAlertPattern, headline, re.IGNORECASE):
        return "OPTIONS"

    return None


def filterIfYouInvested(row):
    headline = str(row.get("headline", "")).strip().lower()

    ifYouInvestedMarkers = [
        r"\bif you invested $\b",
        r"\bhere's how much investing $\b",
    ]

    for marker in ifYouInvestedMarkers:
        if re.search(marker, headline, re.IGNORECASE):
            return "IF_YOU_INVESTED"

    return None


def filterBadTicker(row, validTickers):
    tickers = row.get("tickers", [])
    if tickers is None or len(tickers) == 0:
        return None

    # Check if ALL tickers are NOT in validTickers
    allInvalid = all(symbol.upper() not in validTickers for symbol in tickers)

    if allInvalid:
        return "BAD_TICKER"

    return None


# ---------------------------------------------------------------------------
# The ordered filter pipeline. First match wins.
# ---------------------------------------------------------------------------
FILTER_PIPELINE = [
    (filterBenzingaInsights, "BENZINGA_INSIGHTS"),
    (filterAutomated, "AUTOMATED"),
    (filterTradingHalt, "TRADING_HALT"),
    (filterDataFeed, "DATA_FEED"),
    (filterTranscripts, "TRANSCRIPT"),
    (filterOptions, "OPTIONS"),
    (filterIfYouInvested, "IF_YOU_INVESTED"),
]
